window.DRIVE_PULSE_DATA = {
  "project": {
    "name": "DrivePulse",
    "version": "0.1.0",
    "generatedAt": "2026-03-30T09:49:54+00:00",
    "sourcePath": "data-source/INDEX.snapshot.md",
    "designBasis": [
      "Live filesystem scan captured into a bundled snapshot",
      "Git, README, test, paper, and Pages signal extraction",
      "Static GitHub Pages dashboard"
    ]
  },
  "metrics": {
    "generatedAt": "2026-03-30T09:49:54+00:00",
    "sourcePath": "data-source/INDEX.snapshot.md",
    "trackedProjects": 134,
    "uniquePaths": 107,
    "specificPaths": 105,
    "genericPaths": 2,
    "existingSpecificPaths": 105,
    "missingSpecificPaths": 0,
    "gitRepos": 90,
    "dirtyGitRepos": 6,
    "readmePaths": 63,
    "testMarkedPaths": 96,
    "paperPaths": 90,
    "protocolPaths": 87,
    "pagesReadyPaths": 83,
    "freshOrRecentPaths": 94,
    "evidenceRichPaths": 90
  },
  "tierSignals": [
    {
      "tier": "Tier 4",
      "meanSignals": 7.8,
      "paths": 20,
      "missing": 0
    },
    {
      "tier": "Tier 7",
      "meanSignals": 7.8,
      "paths": 6,
      "missing": 0
    },
    {
      "tier": "Tier 3",
      "meanSignals": 7.3,
      "paths": 6,
      "missing": 0
    },
    {
      "tier": "Tier 2",
      "meanSignals": 6.6,
      "paths": 8,
      "missing": 0
    },
    {
      "tier": "Tier 1",
      "meanSignals": 6.4,
      "paths": 7,
      "missing": 0
    },
    {
      "tier": "Tier 9",
      "meanSignals": 6.4,
      "paths": 5,
      "missing": 0
    },
    {
      "tier": "Tier 6",
      "meanSignals": 6.1,
      "paths": 8,
      "missing": 0
    },
    {
      "tier": "Tier 5",
      "meanSignals": 5.4,
      "paths": 7,
      "missing": 0
    },
    {
      "tier": "Tier 10",
      "meanSignals": 5.1,
      "paths": 32,
      "missing": 0
    },
    {
      "tier": "Tier 11",
      "meanSignals": 2.4,
      "paths": 5,
      "missing": 0
    },
    {
      "tier": "Tier 8",
      "meanSignals": 1.7,
      "paths": 3,
      "missing": 0
    },
    {
      "tier": "Tier 12",
      "meanSignals": 0.0,
      "paths": 1,
      "missing": 0
    }
  ],
  "recentPaths": [
    {
      "path": "C:\\AdaptSim\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T14:31:31+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "AdaptSim"
      ],
      "linkedTiers": [
        "Tier 1"
      ],
      "hasReadme": false,
      "hasManifest": false,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        ".html": 5,
        ".md": 6,
        ".sh": 1,
        "<none>": 7,
        ".sample": 14,
        ".json": 2,
        ".png": 9,
        ".pdf": 3,
        ".py": 3,
        ".pyc": 2
      },
      "sampleFiles": [
        "adaptsim.html",
        "cover_letter_lancet_dh.md",
        "index.html",
        "manuscript_lancet_dh.md",
        "push.sh",
        "review-findings.md",
        ".git/COMMIT_EDITMSG",
        ".git/config",
        ".git/description",
        ".git/HEAD",
        ".git/index",
        ".git/hooks/applypatch-msg.sample",
        ".git/hooks/commit-msg.sample",
        ".git/hooks/fsmonitor-watchman.sample",
        ".git/hooks/post-update.sample",
        ".git/hooks/pre-applypatch.sample",
        ".git/hooks/pre-commit.sample",
        ".git/hooks/pre-merge-commit.sample",
        ".git/hooks/pre-push.sample",
        ".git/hooks/pre-rebase.sample",
        ".git/hooks/pre-receive.sample",
        ".git/hooks/prepare-commit-msg.sample",
        ".git/hooks/push-to-checkout.sample",
        ".git/hooks/sendemail-validate.sample"
      ],
      "scannedFiles": 52,
      "scanTruncated": false,
      "operationalSignals": 6,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "9bd4eb0",
      "gitDirty": false
    },
    {
      "path": "C:\\AlMizan\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T14:31:31+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "Al-Mizan"
      ],
      "linkedTiers": [
        "Tier 1"
      ],
      "hasReadme": false,
      "hasManifest": false,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        ".html": 5,
        ".md": 5,
        ".sh": 1,
        ".py": 3,
        "<none>": 7,
        ".sample": 14,
        ".json": 2,
        ".pyc": 3
      },
      "sampleFiles": [
        "al-mizan.html",
        "cover_letter_bmj_ebm.md",
        "index.html",
        "manuscript_bmj_ebm.md",
        "push.sh",
        "test_al_mizan.py",
        ".git/COMMIT_EDITMSG",
        ".git/config",
        ".git/description",
        ".git/HEAD",
        ".git/index",
        ".git/hooks/applypatch-msg.sample",
        ".git/hooks/commit-msg.sample",
        ".git/hooks/fsmonitor-watchman.sample",
        ".git/hooks/post-update.sample",
        ".git/hooks/pre-applypatch.sample",
        ".git/hooks/pre-commit.sample",
        ".git/hooks/pre-merge-commit.sample",
        ".git/hooks/pre-push.sample",
        ".git/hooks/pre-rebase.sample",
        ".git/hooks/pre-receive.sample",
        ".git/hooks/prepare-commit-msg.sample",
        ".git/hooks/push-to-checkout.sample",
        ".git/hooks/sendemail-validate.sample"
      ],
      "scannedFiles": 40,
      "scanTruncated": false,
      "operationalSignals": 6,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "d3b4b67",
      "gitDirty": false
    },
    {
      "path": "C:\\BenfordMA\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-29T09:26:04+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "BenfordMA"
      ],
      "linkedTiers": [
        "Tier 10"
      ],
      "hasReadme": false,
      "hasManifest": false,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        ".html": 5,
        ".py": 2,
        ".sh": 1,
        "<none>": 7,
        ".sample": 14,
        ".json": 4,
        ".md": 3
      },
      "sampleFiles": [
        "benford-ma.html",
        "build_digits.py",
        "index.html",
        "push.sh",
        ".git/COMMIT_EDITMSG",
        ".git/config",
        ".git/description",
        ".git/HEAD",
        ".git/index",
        ".git/hooks/applypatch-msg.sample",
        ".git/hooks/commit-msg.sample",
        ".git/hooks/fsmonitor-watchman.sample",
        ".git/hooks/post-update.sample",
        ".git/hooks/pre-applypatch.sample",
        ".git/hooks/pre-commit.sample",
        ".git/hooks/pre-merge-commit.sample",
        ".git/hooks/pre-push.sample",
        ".git/hooks/pre-rebase.sample",
        ".git/hooks/pre-receive.sample",
        ".git/hooks/prepare-commit-msg.sample",
        ".git/hooks/push-to-checkout.sample",
        ".git/hooks/sendemail-validate.sample",
        ".git/hooks/update.sample",
        ".git/info/exclude"
      ],
      "scannedFiles": 36,
      "scanTruncated": false,
      "operationalSignals": 6,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "dfe3760",
      "gitDirty": false
    },
    {
      "path": "C:\\BiasForensics\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T14:31:31+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "Bias Forensics"
      ],
      "linkedTiers": [
        "Tier 1"
      ],
      "hasReadme": false,
      "hasManifest": false,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        ".md": 5,
        ".py": 6,
        ".html": 5,
        ".sh": 1,
        "<none>": 7,
        ".sample": 14,
        ".csv": 1,
        ".json": 3,
        ".png": 9,
        ".pdf": 3,
        ".pyc": 5,
        ".r": 1
      },
      "sampleFiles": [
        "cover_letter_rsm.md",
        "generate_figures.py",
        "index.html",
        "manuscript_rsm.md",
        "push.sh",
        ".git/COMMIT_EDITMSG",
        ".git/config",
        ".git/description",
        ".git/HEAD",
        ".git/index",
        ".git/hooks/applypatch-msg.sample",
        ".git/hooks/commit-msg.sample",
        ".git/hooks/fsmonitor-watchman.sample",
        ".git/hooks/post-update.sample",
        ".git/hooks/pre-applypatch.sample",
        ".git/hooks/pre-commit.sample",
        ".git/hooks/pre-merge-commit.sample",
        ".git/hooks/pre-push.sample",
        ".git/hooks/pre-rebase.sample",
        ".git/hooks/pre-receive.sample",
        ".git/hooks/prepare-commit-msg.sample",
        ".git/hooks/push-to-checkout.sample",
        ".git/hooks/sendemail-validate.sample",
        ".git/hooks/update.sample"
      ],
      "scannedFiles": 60,
      "scanTruncated": false,
      "operationalSignals": 6,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "59a3e64",
      "gitDirty": false
    },
    {
      "path": "C:\\EvidenceHalfLife\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T14:31:31+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "Evidence Half-Life"
      ],
      "linkedTiers": [
        "Tier 10"
      ],
      "hasReadme": false,
      "hasManifest": false,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        ".html": 5,
        ".py": 2,
        ".sh": 1,
        ".md": 4,
        "<none>": 7,
        ".sample": 14,
        ".csv": 2,
        ".json": 3,
        ".pyc": 2
      },
      "sampleFiles": [
        "index.html",
        "pipeline.py",
        "push.sh",
        "review-findings.md",
        ".git/COMMIT_EDITMSG",
        ".git/config",
        ".git/description",
        ".git/HEAD",
        ".git/index",
        ".git/hooks/applypatch-msg.sample",
        ".git/hooks/commit-msg.sample",
        ".git/hooks/fsmonitor-watchman.sample",
        ".git/hooks/post-update.sample",
        ".git/hooks/pre-applypatch.sample",
        ".git/hooks/pre-commit.sample",
        ".git/hooks/pre-merge-commit.sample",
        ".git/hooks/pre-push.sample",
        ".git/hooks/pre-rebase.sample",
        ".git/hooks/pre-receive.sample",
        ".git/hooks/prepare-commit-msg.sample",
        ".git/hooks/push-to-checkout.sample",
        ".git/hooks/sendemail-validate.sample",
        ".git/hooks/update.sample",
        ".git/info/exclude"
      ],
      "scannedFiles": 40,
      "scanTruncated": false,
      "operationalSignals": 6,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "9d61de0",
      "gitDirty": false
    },
    {
      "path": "C:\\EvidenceQuality\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T14:31:31+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "EvidenceQuality (Concordance)"
      ],
      "linkedTiers": [
        "Tier 10"
      ],
      "hasReadme": true,
      "hasManifest": false,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        "<none>": 8,
        ".py": 5,
        ".html": 7,
        ".sh": 1,
        ".md": 5,
        ".sample": 14,
        ".json": 7,
        ".csv": 2,
        ".pyc": 5
      },
      "sampleFiles": [
        ".gitignore",
        "build_concordance.py",
        "build_dashboard.py",
        "build_unified.py",
        "dashboard.html",
        "index.html",
        "push.sh",
        "README.md",
        "review-findings.md",
        "run_all.py",
        ".git/COMMIT_EDITMSG",
        ".git/config",
        ".git/description",
        ".git/HEAD",
        ".git/index",
        ".git/hooks/applypatch-msg.sample",
        ".git/hooks/commit-msg.sample",
        ".git/hooks/fsmonitor-watchman.sample",
        ".git/hooks/post-update.sample",
        ".git/hooks/pre-applypatch.sample",
        ".git/hooks/pre-commit.sample",
        ".git/hooks/pre-merge-commit.sample",
        ".git/hooks/pre-push.sample",
        ".git/hooks/pre-rebase.sample"
      ],
      "scannedFiles": 54,
      "scanTruncated": false,
      "operationalSignals": 7,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "8e2ddb6",
      "gitDirty": false
    },
    {
      "path": "C:\\FragilityAtlas\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T14:31:31+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "Fragility Atlas"
      ],
      "linkedTiers": [
        "Tier 1"
      ],
      "hasReadme": false,
      "hasManifest": true,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        "<none>": 8,
        ".json": 6,
        ".md": 7,
        ".py": 14,
        ".html": 5,
        ".sh": 1,
        ".txt": 1,
        ".sample": 14,
        ".csv": 4,
        ".png": 12,
        ".pdf": 4,
        ".pyc": 12,
        ".r": 4
      },
      "sampleFiles": [
        ".gitignore",
        ".zenodo.json",
        "cover_letter_bmj.md",
        "generate_figures.py",
        "index.html",
        "manuscript_bmj.md",
        "push.sh",
        "requirements.txt",
        "review-findings.md",
        ".git/COMMIT_EDITMSG",
        ".git/config",
        ".git/description",
        ".git/HEAD",
        ".git/index",
        ".git/hooks/applypatch-msg.sample",
        ".git/hooks/commit-msg.sample",
        ".git/hooks/fsmonitor-watchman.sample",
        ".git/hooks/post-update.sample",
        ".git/hooks/pre-applypatch.sample",
        ".git/hooks/pre-commit.sample",
        ".git/hooks/pre-merge-commit.sample",
        ".git/hooks/pre-push.sample",
        ".git/hooks/pre-rebase.sample",
        ".git/hooks/pre-receive.sample"
      ],
      "scannedFiles": 92,
      "scanTruncated": false,
      "operationalSignals": 7,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "6040096",
      "gitDirty": false
    },
    {
      "path": "C:\\HTML apps\\DTA_Pro_Review\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T18:12:28+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "DTA Pro"
      ],
      "linkedTiers": [
        "Tier 2"
      ],
      "hasReadme": true,
      "hasManifest": false,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        ".js": 6,
        ".md": 43,
        ".py": 7,
        ".html": 8,
        ".bak": 1,
        ".docx": 4,
        ".png": 43,
        "<none>": 8,
        ".sh": 1,
        ".r": 9,
        ".json": 17,
        ".txt": 1,
        ".sample": 14,
        ".yml": 1,
        ".eps": 11,
        ".tiff": 11,
        ".csv": 5,
        ".ps1": 5,
        ".pyc": 8
      },
      "sampleFiles": [
        "accessibility_enhancements.js",
        "CHANGELOG.md",
        "CLAUDE.md",
        "comprehensive_test_suite.py",
        "dta-pro-v3.7.html",
        "dta-pro-v3.7.html.bak",
        "dta-pro.html",
        "DTA_Pro_PLOS_ONE_Manuscript.md",
        "DTA_Pro_PLOS_ONE_Manuscript_Final.md",
        "DTA_Pro_PLOS_ONE_Manuscript_Formatted.md",
        "F1000_4Persona_LookOnly_Review.md",
        "F1000_Cover_Letter.docx",
        "F1000_Cover_Letter.md",
        "F1000_MultiPersona_Peer_Review.md",
        "f1000_screenshot.png",
        "F1000_Software_Tool_Article.docx",
        "F1000_Software_Tool_Article.md",
        "F1000_Submission_Checklist_RealReview.md",
        "F1000_Truth_4Persona_Review.md",
        "F1000_Word_Expert_Review.md",
        "Improvements_Summary_v4.8.md",
        "index.html",
        "LICENSE",
        "Multi_Persona_Review_Report.md"
      ],
      "scannedFiles": 203,
      "scanTruncated": false,
      "operationalSignals": 7,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "a3146d1",
      "gitDirty": false
    },
    {
      "path": "C:\\HTML apps\\HTA\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T14:31:31+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "HTA Artifact Standard"
      ],
      "linkedTiers": [
        "Tier 2"
      ],
      "hasReadme": true,
      "hasManifest": true,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        "<none>": 286,
        ".md": 314,
        ".py": 24,
        ".cff": 1,
        ".js": 268,
        ".docx": 2,
        ".png": 54,
        ".ico": 1,
        ".html": 8,
        ".json": 279,
        ".sh": 1,
        ".r": 1,
        ".sample": 14,
        ".yml": 15,
        ".xml": 1,
        ".info": 1,
        ".css": 2,
        ".eps": 11,
        ".tiff": 11,
        ".cmd": 22,
        ".ps1": 22,
        ".ts": 113,
        ".txt": 17,
        ".mjs": 7,
        ".lock": 1,
        ".markdown": 5,
        ".mdown": 1,
        ".closure-compiler": 1,
        ".esprima": 1,
        ".mts": 1,
        ".bsd": 4,
        ".cjs": 6,
        ".flow": 1,
        ".map": 2,
        ".svg": 1,
        ".bnf": 1
      },
      "sampleFiles": [
        ".gitignore",
        ".npmignore",
        "BENCHMARK_VS_TREEAGE.md",
        "CHANGELOG.md",
        "check_warnings.py",
        "CITATION.cff",
        "EDITORIAL_FIXES_APPLIED.md",
        "EDITORIAL_REVIEW_RESEARCH_SYNTHESIS_METHODS.md",
        "EDITORIAL_REVIEW_RSM_JANUARY_2026.md",
        "eslint.config.js",
        "F1000_4Persona_LookOnly_Review.md",
        "F1000_Cover_Letter.docx",
        "F1000_Cover_Letter.md",
        "F1000_MultiPersona_Peer_Review.md",
        "f1000_screenshot.png",
        "F1000_Software_Tool_Article.docx",
        "F1000_Software_Tool_Article.md",
        "F1000_Submission_Checklist_RealReview.md",
        "F1000_Truth_4Persona_Review.md",
        "F1000_Word_Expert_Review.md",
        "favicon.ico",
        "gui_review.py",
        "index.html",
        "LICENSE"
      ],
      "scannedFiles": 1500,
      "scanTruncated": true,
      "operationalSignals": 8,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "9c442ee",
      "gitDirty": false
    },
    {
      "path": "C:\\HTML apps\\IPD-Meta-Pro\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T14:31:31+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "IPD-Meta-Pro"
      ],
      "linkedTiers": [
        "Tier 2"
      ],
      "hasReadme": true,
      "hasManifest": false,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        "<none>": 12,
        ".md": 54,
        ".docx": 4,
        ".png": 40,
        ".html": 10,
        ".bak": 1,
        ".sh": 1,
        ".txt": 1,
        ".sample": 14,
        ".yml": 1,
        ".cfg": 1,
        ".12": 1,
        ".py": 67,
        ".json": 26,
        ".r": 4,
        ".js": 65,
        ".eps": 11,
        ".tiff": 11
      },
      "sampleFiles": [
        ".gitignore",
        "BEYOND_R_40_FEATURES.md",
        "CHANGELOG.md",
        "CLAUDE.md",
        "EDITORIAL_REVIEW_RSM.md",
        "EDITORIAL_REVIEW_RSM_2025.md",
        "F1000_4Persona_LookOnly_Review.md",
        "F1000_Cover_Letter.docx",
        "F1000_Cover_Letter.md",
        "F1000_MultiPersona_Peer_Review.md",
        "f1000_screenshot.png",
        "F1000_Software_Tool_Article.docx",
        "F1000_Software_Tool_Article.md",
        "F1000_Submission_Checklist_RealReview.md",
        "F1000_Truth_4Persona_Review.md",
        "F1000_Word_Expert_Review.md",
        "index.html",
        "ipd-meta-pro.html",
        "ipd-meta-pro.html.bak",
        "IPD_Meta_Analysis_Pro_PLOS_ONE_Paper.md",
        "IPD_Meta_Pro_PLOS_ONE_Manuscript.md",
        "LICENSE",
        "PLOS_ONE_Cover_Letter.md",
        "PLOS_ONE_Cover_Letter_Final.md"
      ],
      "scannedFiles": 324,
      "scanTruncated": false,
      "operationalSignals": 7,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "1de6564",
      "gitDirty": false
    },
    {
      "path": "C:\\HTML apps\\NMAhtml\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T14:31:31+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "NMA apps"
      ],
      "linkedTiers": [
        "Tier 2"
      ],
      "hasReadme": true,
      "hasManifest": false,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        "<none>": 16,
        ".js": 22,
        ".py": 6,
        ".md": 30,
        ".txt": 7,
        ".log": 3,
        ".docx": 4,
        ".png": 40,
        ".html": 51,
        ".backup": 1,
        ".enhancements_backup": 1,
        ".final_backup": 1,
        ".methodology_backup": 1,
        ".phase3_backup": 1,
        ".pre-fix": 1,
        ".pre_perfect_backup": 1,
        ".rubin_backup": 1,
        ".backup_pre_cutting_edge": 1,
        ".pre_gapfill_backup": 1,
        ".r": 2,
        ".sh": 1,
        ".json": 26,
        ".ps1": 4,
        ".bat": 1,
        ".sample": 14,
        ".lock": 1,
        ".toml": 1,
        ".wasm": 1,
        ".rs": 1,
        ".tag": 1,
        ".eps": 11,
        ".tiff": 11,
        ".cmd": 2,
        ".ts": 3,
        ".mjs": 4,
        ".csv": 4,
        ".pyc": 3
      },
      "sampleFiles": [
        ".gitignore",
        ".tmp_bind_check.js",
        ".tmp_export_readiness.js",
        ".tmp_gate_pass_flow.js",
        ".tmp_gate_pass_flow_fast.js",
        ".tmp_i18n_smoke.js",
        ".tmp_i18n_smoke2.js",
        ".tmp_nma_smoke_local.js",
        ".tmp_nma_v8_script.js",
        ".tmp_playwright_check_all.spec.js",
        ".tmp_playwright_full_smoke.spec.js",
        ".tmp_recheck_runtime.js",
        ".tmp_selenium_gate_pass.py",
        ".tmp_smoke_ext.js",
        ".tmp_smoke_ext2.js",
        ".tmp_smoke_hardening.js",
        "ACCESSIBILITY-FEATURES.md",
        "benchmark_selenium_vs_r.py",
        "benchmark_suite_selenium_vs_r.py",
        "CHANGELOG.md",
        "CHANGES-SUMMARY.txt",
        "COMPARISON_ADJUSTED_FUNNEL_IMPLEMENTATION.md",
        "ctgov_proxy.err.log",
        "ctgov_proxy.log"
      ],
      "scannedFiles": 280,
      "scanTruncated": false,
      "operationalSignals": 7,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "bac45fc",
      "gitDirty": false
    },
    {
      "path": "C:\\HTML apps\\Pairwiseai\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T18:13:32+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "Pairwise AI"
      ],
      "linkedTiers": [
        "Tier 2"
      ],
      "hasReadme": true,
      "hasManifest": false,
      "hasIndexHtml": false,
      "hasNoJekyll": false,
      "hasE156Bundle": false,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        "<none>": 9,
        ".py": 15,
        ".js": 9,
        ".backup-20260113-112358": 2,
        ".backup-pre-release": 2,
        ".bak": 2,
        ".md": 43,
        ".csv": 5,
        ".docx": 2,
        ".png": 1,
        ".html": 29,
        ".yaml": 2,
        ".sh": 3,
        ".json": 7,
        ".txt": 8,
        ".ps1": 7,
        ".bat": 3,
        ".r": 9,
        ".log": 1,
        ".sample": 14
      },
      "sampleFiles": [
        ".Rhistory",
        "add_advanced_features.py",
        "add_all_features.py",
        "add_missing_functions.py",
        "app.js",
        "app.js.backup-20260113-112358",
        "app.js.backup-pre-release",
        "app.js.bak",
        "app.min.js",
        "app_beautified.js",
        "app_fixed.js",
        "app_test.js",
        "BLOCKER_REMEDIATION_STATUS_2026-02-26.md",
        "CHANGELOG.md",
        "CLAUDE.md",
        "cleanup_duplicates.py",
        "debug_bias_panel.py",
        "DEVELOPMENT_LOG.md",
        "DOCUMENTATION.md",
        "EDITORIAL_REVIEW.md",
        "EXPERT_INVITE_EMAIL_TEMPLATES_2026-02-26.md",
        "EXPERT_REVIEW_OUTREACH_PACK_2026-02-26.md",
        "EXPERT_REVIEW_TRACKER_TEMPLATE.csv",
        "EXPERT_SCORING_ROUND2_2026-02-26.csv"
      ],
      "scannedFiles": 173,
      "scanTruncated": false,
      "operationalSignals": 5,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "860d072",
      "gitDirty": false
    }
  ],
  "evidenceRichPaths": [
    {
      "path": "C:\\HTML apps\\HTA\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T14:31:31+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "HTA Artifact Standard"
      ],
      "linkedTiers": [
        "Tier 2"
      ],
      "hasReadme": true,
      "hasManifest": true,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        "<none>": 286,
        ".md": 314,
        ".py": 24,
        ".cff": 1,
        ".js": 268,
        ".docx": 2,
        ".png": 54,
        ".ico": 1,
        ".html": 8,
        ".json": 279,
        ".sh": 1,
        ".r": 1,
        ".sample": 14,
        ".yml": 15,
        ".xml": 1,
        ".info": 1,
        ".css": 2,
        ".eps": 11,
        ".tiff": 11,
        ".cmd": 22,
        ".ps1": 22,
        ".ts": 113,
        ".txt": 17,
        ".mjs": 7,
        ".lock": 1,
        ".markdown": 5,
        ".mdown": 1,
        ".closure-compiler": 1,
        ".esprima": 1,
        ".mts": 1,
        ".bsd": 4,
        ".cjs": 6,
        ".flow": 1,
        ".map": 2,
        ".svg": 1,
        ".bnf": 1
      },
      "sampleFiles": [
        ".gitignore",
        ".npmignore",
        "BENCHMARK_VS_TREEAGE.md",
        "CHANGELOG.md",
        "check_warnings.py",
        "CITATION.cff",
        "EDITORIAL_FIXES_APPLIED.md",
        "EDITORIAL_REVIEW_RESEARCH_SYNTHESIS_METHODS.md",
        "EDITORIAL_REVIEW_RSM_JANUARY_2026.md",
        "eslint.config.js",
        "F1000_4Persona_LookOnly_Review.md",
        "F1000_Cover_Letter.docx",
        "F1000_Cover_Letter.md",
        "F1000_MultiPersona_Peer_Review.md",
        "f1000_screenshot.png",
        "F1000_Software_Tool_Article.docx",
        "F1000_Software_Tool_Article.md",
        "F1000_Submission_Checklist_RealReview.md",
        "F1000_Truth_4Persona_Review.md",
        "F1000_Word_Expert_Review.md",
        "favicon.ico",
        "gui_review.py",
        "index.html",
        "LICENSE"
      ],
      "scannedFiles": 1500,
      "scanTruncated": true,
      "operationalSignals": 8,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "9c442ee",
      "gitDirty": false
    },
    {
      "path": "C:\\HTML apps\\living-meta\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T14:31:31+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "Living-Meta"
      ],
      "linkedTiers": [
        "Tier 2"
      ],
      "hasReadme": true,
      "hasManifest": true,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        ".md": 323,
        ".yml": 16,
        "<none>": 286,
        ".docx": 2,
        ".png": 34,
        ".html": 7,
        ".json": 268,
        ".js": 296,
        ".sh": 1,
        ".py": 1,
        ".sample": 14,
        ".conf": 2,
        ".eps": 11,
        ".tiff": 11,
        ".cmd": 27,
        ".ps1": 27,
        ".ts": 127,
        ".txt": 13,
        ".mjs": 7,
        ".lock": 1,
        ".markdown": 6,
        ".closure-compiler": 1,
        ".esprima": 1,
        ".mts": 2,
        ".bsd": 2,
        ".cjs": 3,
        ".cts": 1,
        ".svg": 1,
        ".mdown": 1,
        ".map": 1,
        ".bnf": 1,
        ".css": 6
      },
      "sampleFiles": [
        "CHANGELOG.md",
        "CONTRIBUTING.md",
        "docker-compose.yml",
        "Dockerfile",
        "F1000_4Persona_LookOnly_Review.md",
        "F1000_Cover_Letter.docx",
        "F1000_Cover_Letter.md",
        "F1000_MultiPersona_Peer_Review.md",
        "f1000_screenshot.png",
        "F1000_Software_Tool_Article.docx",
        "F1000_Software_Tool_Article.md",
        "F1000_Submission_Checklist_RealReview.md",
        "F1000_Truth_4Persona_Review.md",
        "F1000_Word_Expert_Review.md",
        "index.html",
        "LICENSE",
        "living-meta-complete.html",
        "package-lock.json",
        "package-scripts.json",
        "package.json",
        "PLOS_ONE_Manuscript.md",
        "postcss.config.js",
        "push.sh",
        "README.md"
      ],
      "scannedFiles": 1500,
      "scanTruncated": true,
      "operationalSignals": 8,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "cd106d0",
      "gitDirty": false
    },
    {
      "path": "C:\\Models\\CRES\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T18:14:55+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "CRES"
      ],
      "linkedTiers": [
        "Tier 4"
      ],
      "hasReadme": true,
      "hasManifest": true,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        "<none>": 9,
        ".json": 3,
        ".md": 18,
        ".yml": 1,
        ".docx": 2,
        ".html": 5,
        ".sh": 1,
        ".py": 1,
        ".r": 2,
        ".sample": 14,
        ".csv": 1
      },
      "sampleFiles": [
        ".gitignore",
        ".zenodo.json",
        "CHANGELOG.md",
        "environment.yml",
        "F1000_Concrete_Submission_Fixes.md",
        "F1000_Cover_Letter.docx",
        "F1000_Cover_Letter.md",
        "F1000_MultiPersona_Review.md",
        "F1000_Reviewer_Rerun_Manifest.md",
        "F1000_Software_Tool_Article.docx",
        "F1000_Software_Tool_Article.md",
        "F1000_Submission_Checklist_RealReview.md",
        "fin.html",
        "index.html",
        "LICENSE",
        "manuscript_cres_plos_one.md",
        "manuscript_cres_v4.md",
        "prospero_registration.md",
        "push.sh",
        "README.md",
        "SUBMISSION_CHECKLIST.md",
        "test_fin_selenium.py",
        "validate_comprehensive.R",
        "validate_metafor.R"
      ],
      "scannedFiles": 57,
      "scanTruncated": false,
      "operationalSignals": 8,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "9bd2afd",
      "gitDirty": false
    },
    {
      "path": "C:\\Models\\FATIHA_Project\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T18:15:23+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "SYNTHESIS (FATIHA)"
      ],
      "linkedTiers": [
        "Tier 4"
      ],
      "hasReadme": true,
      "hasManifest": true,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        "<none>": 16,
        ".json": 4,
        ".md": 41,
        ".docx": 2,
        ".png": 17,
        ".html": 3,
        ".sh": 1,
        ".lock": 1,
        ".csv": 6,
        ".yaml": 2,
        ".sample": 14,
        ".r": 23,
        ".rd": 16,
        ".rmd": 1
      },
      "sampleFiles": [
        ".gitignore",
        ".Rbuildignore",
        ".Rprofile",
        ".zenodo.json",
        "CHANGELOG.md",
        "CONTRIBUTING.md",
        "DESCRIPTION",
        "DESIGN_DECISIONS.md",
        "Dockerfile",
        "F1000_Concrete_Submission_Fixes.md",
        "F1000_Cover_Letter.docx",
        "F1000_Cover_Letter.md",
        "F1000_MultiPersona_Review.md",
        "F1000_Reviewer_Rerun_Manifest.md",
        "F1000_Software_Tool_Article.docx",
        "F1000_Software_Tool_Article.md",
        "F1000_Submission_Checklist_RealReview.md",
        "Final_SYNTHESIS_Diagnostics.png",
        "index.html",
        "LICENSE",
        "NAMESPACE",
        "Performance_Summary.png",
        "push.sh",
        "README.md"
      ],
      "scannedFiles": 147,
      "scanTruncated": false,
      "operationalSignals": 8,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "9912449",
      "gitDirty": false
    },
    {
      "path": "C:\\Models\\GRMA_paper\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T18:15:31+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "GRMA"
      ],
      "linkedTiers": [
        "Tier 4"
      ],
      "hasReadme": true,
      "hasManifest": true,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        "<none>": 10,
        ".json": 5,
        ".r": 8,
        ".md": 16,
        ".py": 7,
        ".docx": 2,
        ".png": 10,
        ".rds": 2,
        ".html": 3,
        ".sh": 1,
        ".txt": 2,
        ".csv": 20,
        ".sample": 14,
        ".pyc": 1
      },
      "sampleFiles": [
        ".gitignore",
        ".zenodo.json",
        "applied_examples.R",
        "CD002042_embedded_data.R",
        "CHANGELOG.md",
        "cross_validate.py",
        "cross_validate.R",
        "dev_analyze_rmse_coverage.py",
        "dev_gen_tables_from_checkpoint.R",
        "dev_resume_simulation.R",
        "F1000_Concrete_Submission_Fixes.md",
        "F1000_Cover_Letter.docx",
        "F1000_Cover_Letter.md",
        "F1000_MultiPersona_Review.md",
        "F1000_Reviewer_Rerun_Manifest.md",
        "F1000_Software_Tool_Article.docx",
        "F1000_Software_Tool_Article.md",
        "F1000_Submission_Checklist_RealReview.md",
        "Fig1_bias_rmse_by_scenario.png",
        "Fig2_coverage_comparison.png",
        "Fig3_guard_ablation.png",
        "Fig4_benchmark_scatter.png",
        "Fig5_benchmark_kband.png",
        "generate_figures.py"
      ],
      "scannedFiles": 101,
      "scanTruncated": false,
      "operationalSignals": 8,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "13fd372",
      "gitDirty": false
    },
    {
      "path": "C:\\Models\\GWAM\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T18:15:39+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "GWAM"
      ],
      "linkedTiers": [
        "Tier 4"
      ],
      "hasReadme": true,
      "hasManifest": true,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        "<none>": 11,
        ".json": 549,
        ".md": 30,
        ".docx": 2,
        ".html": 3,
        ".sh": 1,
        ".txt": 1,
        ".log": 1,
        ".sample": 14,
        ".tag": 1,
        ".yml": 1,
        ".csv": 94,
        ".png": 24,
        ".pdf": 8,
        ".py": 24,
        ".pyc": 24
      },
      "sampleFiles": [
        ".gitignore",
        ".zenodo.json",
        "CHANGELOG.md",
        "F1000_Concrete_Submission_Fixes.md",
        "F1000_Cover_Letter.docx",
        "F1000_Cover_Letter.md",
        "F1000_MultiPersona_Review.md",
        "F1000_Reviewer_Rerun_Manifest.md",
        "F1000_Software_Tool_Article.docx",
        "F1000_Software_Tool_Article.md",
        "F1000_Submission_Checklist_RealReview.md",
        "index.html",
        "LICENSE",
        "paper_review.md",
        "push.sh",
        "README.md",
        "requirements.txt",
        "test-run.log",
        ".git/COMMIT_EDITMSG",
        ".git/config",
        ".git/description",
        ".git/HEAD",
        ".git/index",
        ".git/hooks/applypatch-msg.sample"
      ],
      "scannedFiles": 788,
      "scanTruncated": false,
      "operationalSignals": 8,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "98724b8",
      "gitDirty": false
    },
    {
      "path": "C:\\Models\\HTA_Evidence_Integrity_Suite\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T18:15:46+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "HTA Evidence Integrity"
      ],
      "linkedTiers": [
        "Tier 7"
      ],
      "hasReadme": true,
      "hasManifest": true,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        "<none>": 12,
        ".json": 3,
        ".md": 82,
        ".r": 89,
        ".yml": 1,
        ".docx": 2,
        ".html": 5,
        ".txt": 9,
        ".sh": 1,
        ".sample": 14,
        ".csv": 128,
        ".pdf": 1,
        ".rds": 13,
        ".png": 8,
        ".py": 1
      },
      "sampleFiles": [
        ".gitignore",
        ".zenodo.json",
        "CHANGELOG.md",
        "config_paths.R",
        "DESCRIPTION",
        "environment.yml",
        "F1000_Concrete_Submission_Fixes.md",
        "F1000_Cover_Letter.docx",
        "F1000_Cover_Letter.md",
        "F1000_MultiPersona_Review.md",
        "F1000_Reviewer_Rerun_Manifest.md",
        "F1000_Software_Tool_Article.docx",
        "F1000_Software_Tool_Article.md",
        "F1000_Submission_Checklist_RealReview.md",
        "HTA_Dashboard.html",
        "HTA_IMPACT_REPORT.md",
        "IMPACT_ASSESSMENT_REVIEW.md",
        "index.html",
        "LICENSE",
        "metadata_requirements.txt",
        "MULTIPERSON_REVIEW.md",
        "NAMESPACE",
        "PLOS_ONE_Final_Manuscript.md",
        "PLOS_ONE_FINAL_REVIEW.md"
      ],
      "scannedFiles": 369,
      "scanTruncated": false,
      "operationalSignals": 8,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "40949e7",
      "gitDirty": false
    },
    {
      "path": "C:\\Models\\HTA_Transportability_Engine\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T18:15:53+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "HTA Transportability"
      ],
      "linkedTiers": [
        "Tier 7"
      ],
      "hasReadme": true,
      "hasManifest": true,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        "<none>": 9,
        ".json": 3,
        ".r": 17,
        ".md": 26,
        ".csv": 17,
        ".yml": 1,
        ".docx": 2,
        ".html": 5,
        ".sh": 1,
        ".sample": 14
      },
      "sampleFiles": [
        ".gitignore",
        ".zenodo.json",
        "01_audit_pairwise70.R",
        "02_external_target_sources.md",
        "03_transportability_scaffold.R",
        "04_pairwise70_columns.R",
        "05_build_ctgov_queries.R",
        "06_ctgov_fetch.R",
        "07_ctgov_aggregate.R",
        "08_transportability_merge.R",
        "09_transportability_target_cv.R",
        "10_transportability_domain_cv.R",
        "11_transportability_domain_report.R",
        "12_build_domain_queries.R",
        "13_ctgov_domain_fetch.R",
        "14_ctgov_domain_aggregate.R",
        "CHANGELOG.md",
        "config_paths.R",
        "cte_penalty_model.R",
        "ctgov_domain_covariates.csv",
        "ctgov_domain_query_terms.csv",
        "ctgov_domain_summary.md",
        "ctgov_global_tokens.csv",
        "ctgov_query_terms.csv"
      ],
      "scannedFiles": 95,
      "scanTruncated": false,
      "operationalSignals": 8,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "7374242",
      "gitDirty": false
    },
    {
      "path": "C:\\Models\\HTA_Unified_Intelligence_System\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T18:16:00+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "HTA Unified Intel"
      ],
      "linkedTiers": [
        "Tier 7"
      ],
      "hasReadme": true,
      "hasManifest": true,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        "<none>": 10,
        ".json": 7,
        ".md": 15,
        ".cff": 1,
        ".r": 10,
        ".docx": 2,
        ".rmd": 1,
        ".zip": 1,
        ".html": 5,
        ".ps1": 2,
        ".sh": 1,
        ".txt": 1,
        ".sample": 14,
        ".yml": 1,
        ".png": 11,
        ".csv": 12,
        ".db": 1,
        ".log": 7,
        ".py": 7
      },
      "sampleFiles": [
        ".gitignore",
        ".zenodo.json",
        "CHANGELOG.md",
        "CITATION.cff",
        "config.R",
        "Dockerfile",
        "F1000_Concrete_Submission_Fixes.md",
        "F1000_Cover_Letter.docx",
        "F1000_Cover_Letter.md",
        "F1000_MultiPersona_Review.md",
        "F1000_Reviewer_Rerun_Manifest.md",
        "F1000_Software_Tool_Article.docx",
        "F1000_Software_Tool_Article.md",
        "F1000_Submission_Checklist_RealReview.md",
        "HTA_Intelligence_Manuscript_Nature.md",
        "HTA_Living_Manuscript.Rmd",
        "HTA_Unified_System_Submission.zip",
        "index.html",
        "install_all.ps1",
        "LICENSE",
        "push.sh",
        "README.md",
        "requirements.txt",
        "run_all_unified.ps1"
      ],
      "scannedFiles": 109,
      "scanTruncated": false,
      "operationalSignals": 8,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "05588c3",
      "gitDirty": false
    },
    {
      "path": "C:\\Models\\IPD_QMA\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T18:16:09+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "IPD-QMA"
      ],
      "linkedTiers": [
        "Tier 4"
      ],
      "hasReadme": true,
      "hasManifest": true,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        "<none>": 10,
        ".json": 3,
        ".py": 7,
        ".md": 17,
        ".docx": 5,
        ".html": 3,
        ".txt": 2,
        ".sh": 1,
        ".sample": 14,
        ".csv": 4,
        ".png": 24,
        ".pyc": 4
      },
      "sampleFiles": [
        ".gitignore",
        ".zenodo.json",
        "build_docx.py",
        "CHANGELOG.md",
        "CORRECTIONS.md",
        "F1000_Concrete_Submission_Fixes.md",
        "F1000_Cover_Letter.docx",
        "F1000_Cover_Letter.md",
        "F1000_MultiPersona_Review.md",
        "F1000_Reviewer_Rerun_Manifest.md",
        "F1000_Software_Tool_Article.docx",
        "F1000_Software_Tool_Article.md",
        "F1000_Submission_Checklist_RealReview.md",
        "fetch_nhanes.py",
        "index.html",
        "IPD.docx",
        "IPD_original.docx",
        "ipd_qma.py",
        "IPD_QMA_corrected_draft.md",
        "IPD_QMA_submission.docx",
        "LICENSE",
        "Makefile",
        "paper_text.txt",
        "PLOS_ONE_REVIEW.md"
      ],
      "scannedFiles": 94,
      "scanTruncated": false,
      "operationalSignals": 8,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "b24a155",
      "gitDirty": false
    },
    {
      "path": "C:\\Models\\New_Heterogeneity_Model\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T18:18:12+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "HeterogeneityASE"
      ],
      "linkedTiers": [
        "Tier 4"
      ],
      "hasReadme": true,
      "hasManifest": true,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        "<none>": 12,
        ".json": 3,
        ".r": 12,
        ".md": 44,
        ".yml": 1,
        ".docx": 2,
        ".html": 3,
        ".sh": 1,
        ".sample": 14,
        ".csv": 106,
        ".txt": 7,
        ".rds": 10,
        ".png": 9,
        ".rd": 1,
        ".tiff": 3
      },
      "sampleFiles": [
        ".gitignore",
        ".Rbuildignore",
        ".zenodo.json",
        "benchmark_ase.R",
        "build_heterogeneity_atlas.R",
        "CHANGELOG.md",
        "DESCRIPTION",
        "environment.yml",
        "F1000_Concrete_Submission_Fixes.md",
        "F1000_Cover_Letter.docx",
        "F1000_Cover_Letter.md",
        "F1000_MultiPersona_Review.md",
        "F1000_Reviewer_Rerun_Manifest.md",
        "F1000_Software_Tool_Article.docx",
        "F1000_Software_Tool_Article.md",
        "F1000_Submission_Checklist_RealReview.md",
        "generate_figure1.R",
        "generate_supplementary_figs.R",
        "generate_supplementary_tables.R",
        "index.html",
        "LICENSE",
        "MULTIPERSON_REVIEW.md",
        "NAMESPACE",
        "PLOS_ONE_Manuscript_ASE.md"
      ],
      "scannedFiles": 228,
      "scanTruncated": false,
      "operationalSignals": 8,
      "hasGit": true,
      "gitBranch": "master",
      "gitHead": "4ce31ac",
      "gitDirty": false
    },
    {
      "path": "C:\\Models\\Pairwise70\\",
      "specificPath": true,
      "exists": true,
      "isDirectory": true,
      "lastModified": "2026-03-28T18:18:32+00:00",
      "ageDays": 1,
      "activityBand": "fresh",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "Pairwise70"
      ],
      "linkedTiers": [
        "Tier 6"
      ],
      "hasReadme": true,
      "hasManifest": true,
      "hasIndexHtml": true,
      "hasNoJekyll": false,
      "hasE156Bundle": true,
      "hasProtocolArtifact": true,
      "hasPaperArtifact": true,
      "hasTestsMarker": true,
      "extensionCounts": {
        "<none>": 17,
        ".json": 4,
        ".md": 75,
        ".r": 106,
        ".txt": 20,
        ".yml": 1,
        ".docx": 2,
        ".html": 7,
        ".gz": 1,
        ".rds": 14,
        ".sh": 1,
        ".sample": 14,
        ".csv": 125,
        ".pdf": 1,
        ".png": 8,
        ".rda": 501,
        ".rd": 517,
        ".py": 37,
        ".db": 1,
        ".tag": 1,
        ".pyc": 2
      },
      "sampleFiles": [
        ".gitignore",
        ".Rbuildignore",
        ".RData",
        ".zenodo.json",
        "CHANGELOG.md",
        "check_simulation_status.R",
        "CLAUDE.md",
        "COMPLETE_PROJECT_DOCUMENTATION.md",
        "compress_data.R",
        "convert_to_csv_simple.R",
        "debug_output.txt",
        "debug_output2.txt",
        "debug_output3.txt",
        "debug_spe_tas.R",
        "debug_trimfill.R",
        "DESCRIPTION",
        "EDITORIAL_REVIEW_MAFI_CALCULATOR.md",
        "environment.yml",
        "F1000_Concrete_Submission_Fixes.md",
        "F1000_Cover_Letter.docx",
        "F1000_Cover_Letter.md",
        "F1000_MultiPersona_Review.md",
        "F1000_Reviewer_Rerun_Manifest.md",
        "F1000_Software_Tool_Article.docx"
      ],
      "scannedFiles": 1455,
      "scanTruncated": false,
      "operationalSignals": 8,
      "hasGit": true,
      "gitBranch": "main",
      "gitHead": "a467240",
      "gitDirty": false
    }
  ],
  "missingPaths": [],
  "genericPaths": [
    {
      "path": "(in HTML apps or user home)",
      "specificPath": false,
      "exists": false,
      "reason": "Generic or non-filesystem path; live scan skipped.",
      "linkedProjectCount": 1,
      "linkedProjects": [
        "Synthesis Course"
      ],
      "linkedTiers": [
        "Tier 8"
      ],
      "operationalSignals": 0,
      "activityBand": "generic"
    },
    {
      "path": "C:\\Projects\\",
      "specificPath": false,
      "exists": false,
      "reason": "Generic or non-filesystem path; live scan skipped.",
      "linkedProjectCount": 26,
      "linkedProjects": [
        "advanced-nma-pooling",
        "claude-plugins",
        "claude-rct-work",
        "esc-acs-living-meta",
        "everything-claude-code",
        "evidence-inference",
        "experimental-meta-analysis",
        "glm-code"
      ],
      "linkedTiers": [
        "Tier 12"
      ],
      "operationalSignals": 0,
      "activityBand": "generic"
    }
  ],
  "activityBreakdown": [
    {
      "band": "Fresh",
      "count": 94
    },
    {
      "band": "Warm",
      "count": 11
    }
  ],
  "signalBreakdown": [
    {
      "label": "Git repos",
      "count": 90
    },
    {
      "label": "Dirty git repos",
      "count": 6
    },
    {
      "label": "README paths",
      "count": 63
    },
    {
      "label": "Test-marked paths",
      "count": 96
    },
    {
      "label": "Paper paths",
      "count": 90
    },
    {
      "label": "Protocol paths",
      "count": 87
    },
    {
      "label": "Pages-ready paths",
      "count": 83
    },
    {
      "label": "Evidence-rich paths",
      "count": 90
    }
  ]
};
